enum SessionCloseStatus {
    ILLEGAL_REQUEST = 100,
    HEARTBEAT_TIMEOUT = 110,
    LOGIN_TIMEOUT,
    SWITCH,

    SERVER_ERROR = 200,
    SERVER_CLOSED,
    SERVER_UNAVAILABLE,

    CONNECTION_CLOSED = 300,

    UNKNOWN_ERROR = 400,

    DISCONNECTED_BY_CLIENT = 500,
    DISCONNECTED_BY_OTHER_DEVICE,

    DISCONNECTED_BY_ADMIN = 600,

    USER_IS_DELETED_OR_INACTIVATED = 700,
    USER_IS_BLOCKED
}

export default SessionCloseStatus;