enum TurmsCloseStatus {
    REDIRECT = 4300,
    SWITCH,

    ILLEGAL_REQUEST = 4400,
    HEARTBEAT_TIMEOUT,
    DISCONNECTED_BY_CLIENT,
    DISCONNECTED_BY_OTHER_DEVICE,

    SERVER_ERROR = 4500,
    SERVER_CLOSED,
    SERVER_UNAVAILABLE,

    LOGIN_CONFLICT = 4600,

    DISCONNECTED_BY_ADMIN = 4700,
    USER_IS_DELETED_OR_INACTIVATED,

    UNKNOWN_ERROR = 4900
}
export default TurmsCloseStatus;