enum TurmsCloseStatus {
    SWITCH = 300,

    ILLEGAL_REQUEST = 400,
    HEARTBEAT_TIMEOUT,
    DISCONNECTED_BY_CLIENT,
    DISCONNECTED_BY_OTHER_DEVICE,

    SERVER_ERROR = 500,
    SERVER_CLOSED,
    SERVER_UNAVAILABLE,

    LOGIN_CONFLICT = 600,
    LOGIN_TIMEOUT,

    DISCONNECTED_BY_ADMIN = 700,
    USER_IS_DELETED_OR_INACTIVATED,

    UNKNOWN_ERROR = 900
}

export default TurmsCloseStatus;