// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: model/common/strings_with_version.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_model_2fcommon_2fstrings_5fwith_5fversion_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_model_2fcommon_2fstrings_5fwith_5fversion_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_model_2fcommon_2fstrings_5fwith_5fversion_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_model_2fcommon_2fstrings_5fwith_5fversion_2eproto {
    static const ::uint32_t offsets[];
};
namespace turms {
namespace client {
namespace model {
namespace proto {
class StringsWithVersion;
struct StringsWithVersionDefaultTypeInternal;
extern StringsWithVersionDefaultTypeInternal _StringsWithVersion_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google

namespace turms {
namespace client {
namespace model {
namespace proto {

// ===================================================================

// -------------------------------------------------------------------

class StringsWithVersion final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:turms.client.model.proto.StringsWithVersion) */ {
   public:
    inline StringsWithVersion()
        : StringsWithVersion(nullptr) {
    }
    ~StringsWithVersion() override;
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR StringsWithVersion(
        ::google::protobuf::internal::ConstantInitialized);

    inline StringsWithVersion(const StringsWithVersion& from)
        : StringsWithVersion(nullptr, from) {
    }
    inline StringsWithVersion(StringsWithVersion&& from) noexcept
        : StringsWithVersion(nullptr, std::move(from)) {
    }
    inline StringsWithVersion& operator=(const StringsWithVersion& from) {
        CopyFrom(from);
        return *this;
    }
    inline StringsWithVersion& operator=(StringsWithVersion&& from) noexcept {
        if (this == &from)
            return *this;
        if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
            && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        ) {
            InternalSwap(&from);
        } else {
            CopyFrom(from);
        }
        return *this;
    }

    inline const std::string& unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
        return _internal_metadata_.unknown_fields<std::string>(
            ::google::protobuf::internal::GetEmptyString);
    }
    inline std::string* mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
        return _internal_metadata_.mutable_unknown_fields<std::string>();
    }

    static const StringsWithVersion& default_instance() {
        return *internal_default_instance();
    }
    static inline const StringsWithVersion* internal_default_instance() {
        return reinterpret_cast<const StringsWithVersion*>(&_StringsWithVersion_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;
    friend void swap(StringsWithVersion& a, StringsWithVersion& b) {
        a.Swap(&b);
    }
    inline void Swap(StringsWithVersion* other) {
        if (other == this)
            return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        } else {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(StringsWithVersion* other) {
        if (other == this)
            return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    StringsWithVersion* New(::google::protobuf::Arena* arena = nullptr) const final {
        return ::google::protobuf::MessageLite::DefaultConstruct<StringsWithVersion>(arena);
    }
    void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from) final;
    void CopyFrom(const StringsWithVersion& from);
    void MergeFrom(const StringsWithVersion& from);
    bool IsInitialized() const {
        return true;
    }
    ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
    ::size_t ByteSizeLong() const final;
    ::uint8_t* _InternalSerialize(::uint8_t* target,
                                  ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
    int GetCachedSize() const {
        return _impl_._cached_size_.Get();
    }

   private:
    void SharedCtor(::google::protobuf::Arena* arena);
    void SharedDtor();
    void InternalSwap(StringsWithVersion* other);

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName() {
        return "turms.client.model.proto.StringsWithVersion";
    }

   protected:
    explicit StringsWithVersion(::google::protobuf::Arena* arena);
    StringsWithVersion(::google::protobuf::Arena* arena, const StringsWithVersion& from);
    StringsWithVersion(::google::protobuf::Arena* arena, StringsWithVersion&& from) noexcept
        : StringsWithVersion(arena) {
        *this = ::std::move(from);
    }
    const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

   public:
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    enum : int {
        kStringsFieldNumber = 1,
        kLastUpdatedDateFieldNumber = 2,
    };
    // repeated string strings = 1;
    int strings_size() const;

   private:
    int _internal_strings_size() const;

   public:
    void clear_strings();
    const std::string& strings(int index) const;
    std::string* mutable_strings(int index);
    void set_strings(int index, const std::string& value);
    void set_strings(int index, std::string&& value);
    void set_strings(int index, const char* value);
    void set_strings(int index, const char* value, std::size_t size);
    void set_strings(int index, absl::string_view value);
    std::string* add_strings();
    void add_strings(const std::string& value);
    void add_strings(std::string&& value);
    void add_strings(const char* value);
    void add_strings(const char* value, std::size_t size);
    void add_strings(absl::string_view value);
    const ::google::protobuf::RepeatedPtrField<std::string>& strings() const;
    ::google::protobuf::RepeatedPtrField<std::string>* mutable_strings();

   private:
    const ::google::protobuf::RepeatedPtrField<std::string>& _internal_strings() const;
    ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_strings();

   public:
    // optional int64 last_updated_date = 2;
    bool has_last_updated_date() const;
    void clear_last_updated_date();
    ::int64_t last_updated_date() const;
    void set_last_updated_date(::int64_t value);

   private:
    ::int64_t _internal_last_updated_date() const;
    void _internal_set_last_updated_date(::int64_t value);

   public:
    // @@protoc_insertion_point(class_scope:turms.client.model.proto.StringsWithVersion)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 59, 2> _table_;

    static constexpr const void* _raw_default_instance_ = &_StringsWithVersion_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_ {
        inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena,
                              const Impl_& from,
                              const StringsWithVersion& from_msg);
        ::google::protobuf::internal::HasBits<1> _has_bits_;
        mutable ::google::protobuf::internal::CachedSize _cached_size_;
        ::google::protobuf::RepeatedPtrField<std::string> strings_;
        ::int64_t last_updated_date_;
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    union {
        Impl_ _impl_;
    };
    friend struct ::TableStruct_model_2fcommon_2fstrings_5fwith_5fversion_2eproto;
};

// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StringsWithVersion

// repeated string strings = 1;
inline int StringsWithVersion::_internal_strings_size() const {
    return _internal_strings().size();
}
inline int StringsWithVersion::strings_size() const {
    return _internal_strings_size();
}
inline void StringsWithVersion::clear_strings() {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.strings_.Clear();
}
inline std::string* StringsWithVersion::add_strings() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    std::string* _s = _internal_mutable_strings()->Add();
    // @@protoc_insertion_point(field_add_mutable:turms.client.model.proto.StringsWithVersion.strings)
    return _s;
}
inline const std::string& StringsWithVersion::strings(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
    // @@protoc_insertion_point(field_get:turms.client.model.proto.StringsWithVersion.strings)
    return _internal_strings().Get(index);
}
inline std::string* StringsWithVersion::mutable_strings(int index) ABSL_ATTRIBUTE_LIFETIME_BOUND {
    // @@protoc_insertion_point(field_mutable:turms.client.model.proto.StringsWithVersion.strings)
    return _internal_mutable_strings()->Mutable(index);
}
inline void StringsWithVersion::set_strings(int index, const std::string& value) {
    _internal_mutable_strings()->Mutable(index)->assign(value);
    // @@protoc_insertion_point(field_set:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::set_strings(int index, std::string&& value) {
    _internal_mutable_strings()->Mutable(index)->assign(std::move(value));
    // @@protoc_insertion_point(field_set:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::set_strings(int index, const char* value) {
    ABSL_DCHECK(value != nullptr);
    _internal_mutable_strings()->Mutable(index)->assign(value);
    // @@protoc_insertion_point(field_set_char:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::set_strings(int index, const char* value, std::size_t size) {
    _internal_mutable_strings()->Mutable(index)->assign(reinterpret_cast<const char*>(value), size);
    // @@protoc_insertion_point(field_set_pointer:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::set_strings(int index, absl::string_view value) {
    _internal_mutable_strings()->Mutable(index)->assign(value.data(), value.size());
    // @@protoc_insertion_point(field_set_string_piece:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::add_strings(const std::string& value) {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _internal_mutable_strings()->Add()->assign(value);
    // @@protoc_insertion_point(field_add:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::add_strings(std::string&& value) {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _internal_mutable_strings()->Add(std::move(value));
    // @@protoc_insertion_point(field_add:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::add_strings(const char* value) {
    ABSL_DCHECK(value != nullptr);
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _internal_mutable_strings()->Add()->assign(value);
    // @@protoc_insertion_point(field_add_char:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::add_strings(const char* value, std::size_t size) {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _internal_mutable_strings()->Add()->assign(reinterpret_cast<const char*>(value), size);
    // @@protoc_insertion_point(field_add_pointer:turms.client.model.proto.StringsWithVersion.strings)
}
inline void StringsWithVersion::add_strings(absl::string_view value) {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _internal_mutable_strings()->Add()->assign(value.data(), value.size());
    // @@protoc_insertion_point(field_add_string_piece:turms.client.model.proto.StringsWithVersion.strings)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>& StringsWithVersion::strings() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
    // @@protoc_insertion_point(field_list:turms.client.model.proto.StringsWithVersion.strings)
    return _internal_strings();
}
inline ::google::protobuf::RepeatedPtrField<std::string>* StringsWithVersion::mutable_strings()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
    // @@protoc_insertion_point(field_mutable_list:turms.client.model.proto.StringsWithVersion.strings)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _internal_mutable_strings();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
StringsWithVersion::_internal_strings() const {
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.strings_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
StringsWithVersion::_internal_mutable_strings() {
    ::google::protobuf::internal::TSanRead(&_impl_);
    return &_impl_.strings_;
}

// optional int64 last_updated_date = 2;
inline bool StringsWithVersion::has_last_updated_date() const {
    bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
    return value;
}
inline void StringsWithVersion::clear_last_updated_date() {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.last_updated_date_ = ::int64_t{0};
    _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t StringsWithVersion::last_updated_date() const {
    // @@protoc_insertion_point(field_get:turms.client.model.proto.StringsWithVersion.last_updated_date)
    return _internal_last_updated_date();
}
inline void StringsWithVersion::set_last_updated_date(::int64_t value) {
    _internal_set_last_updated_date(value);
    _impl_._has_bits_[0] |= 0x00000001u;
    // @@protoc_insertion_point(field_set:turms.client.model.proto.StringsWithVersion.last_updated_date)
}
inline ::int64_t StringsWithVersion::_internal_last_updated_date() const {
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.last_updated_date_;
}
inline void StringsWithVersion::_internal_set_last_updated_date(::int64_t value) {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.last_updated_date_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_model_2fcommon_2fstrings_5fwith_5fversion_2eproto_2epb_2eh
