// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/update_user_online_status_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "turms/client/model/proto/constant/user_status.pb.h"
#include "turms/client/model/proto/constant/device_type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto {
  static const ::uint32_t offsets[];
};
namespace turms {
namespace client {
namespace model {
namespace proto {
class UpdateUserOnlineStatusRequest;
struct UpdateUserOnlineStatusRequestDefaultTypeInternal;
extern UpdateUserOnlineStatusRequestDefaultTypeInternal _UpdateUserOnlineStatusRequest_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace turms {
namespace client {
namespace model {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class UpdateUserOnlineStatusRequest final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:turms.client.model.proto.UpdateUserOnlineStatusRequest) */ {
 public:
  inline UpdateUserOnlineStatusRequest() : UpdateUserOnlineStatusRequest(nullptr) {}
  ~UpdateUserOnlineStatusRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateUserOnlineStatusRequest(::google::protobuf::internal::ConstantInitialized);

  UpdateUserOnlineStatusRequest(const UpdateUserOnlineStatusRequest& from);
  UpdateUserOnlineStatusRequest(UpdateUserOnlineStatusRequest&& from) noexcept
    : UpdateUserOnlineStatusRequest() {
    *this = ::std::move(from);
  }

  inline UpdateUserOnlineStatusRequest& operator=(const UpdateUserOnlineStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateUserOnlineStatusRequest& operator=(UpdateUserOnlineStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const UpdateUserOnlineStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateUserOnlineStatusRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateUserOnlineStatusRequest*>(
               &_UpdateUserOnlineStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpdateUserOnlineStatusRequest& a, UpdateUserOnlineStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateUserOnlineStatusRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateUserOnlineStatusRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateUserOnlineStatusRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateUserOnlineStatusRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const UpdateUserOnlineStatusRequest& from);
  void MergeFrom(const UpdateUserOnlineStatusRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateUserOnlineStatusRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "turms.client.model.proto.UpdateUserOnlineStatusRequest";
  }
  protected:
  explicit UpdateUserOnlineStatusRequest(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceTypesFieldNumber = 1,
    kUserStatusFieldNumber = 2,
  };
  // repeated .turms.client.model.proto.DeviceType device_types = 1;
  int device_types_size() const;
  private:
  int _internal_device_types_size() const;

  public:
  void clear_device_types() ;
  public:
  ::turms::client::model::proto::DeviceType device_types(int index) const;
  void set_device_types(int index, ::turms::client::model::proto::DeviceType value);
  void add_device_types(::turms::client::model::proto::DeviceType value);
  const ::google::protobuf::RepeatedField<int>& device_types() const;
  ::google::protobuf::RepeatedField<int>* mutable_device_types();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_device_types() const;
  ::google::protobuf::RepeatedField<int>* _internal_mutable_device_types();

  public:
  // .turms.client.model.proto.UserStatus user_status = 2;
  void clear_user_status() ;
  ::turms::client::model::proto::UserStatus user_status() const;
  void set_user_status(::turms::client::model::proto::UserStatus value);

  private:
  ::turms::client::model::proto::UserStatus _internal_user_status() const;
  void _internal_set_user_status(::turms::client::model::proto::UserStatus value);

  public:
  // @@protoc_insertion_point(class_scope:turms.client.model.proto.UpdateUserOnlineStatusRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedField<int> device_types_;
    mutable ::google::protobuf::internal::CachedSize _device_types_cached_byte_size_;
    int user_status_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UpdateUserOnlineStatusRequest

// repeated .turms.client.model.proto.DeviceType device_types = 1;
inline int UpdateUserOnlineStatusRequest::_internal_device_types_size() const {
  return _internal_device_types().size();
}
inline int UpdateUserOnlineStatusRequest::device_types_size() const {
  return _internal_device_types_size();
}
inline void UpdateUserOnlineStatusRequest::clear_device_types() {
  _internal_mutable_device_types()->Clear();
}
inline ::turms::client::model::proto::DeviceType UpdateUserOnlineStatusRequest::device_types(int index) const {
  // @@protoc_insertion_point(field_get:turms.client.model.proto.UpdateUserOnlineStatusRequest.device_types)
  return static_cast<::turms::client::model::proto::DeviceType>(_internal_device_types().Get(index));
}
inline void UpdateUserOnlineStatusRequest::set_device_types(int index, ::turms::client::model::proto::DeviceType value) {
  _internal_mutable_device_types()->Set(index, value);
  // @@protoc_insertion_point(field_set:turms.client.model.proto.UpdateUserOnlineStatusRequest.device_types)
}
inline void UpdateUserOnlineStatusRequest::add_device_types(::turms::client::model::proto::DeviceType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_device_types()->Add(value);
  // @@protoc_insertion_point(field_add:turms.client.model.proto.UpdateUserOnlineStatusRequest.device_types)
}
inline const ::google::protobuf::RepeatedField<int>& UpdateUserOnlineStatusRequest::device_types() const {
  // @@protoc_insertion_point(field_list:turms.client.model.proto.UpdateUserOnlineStatusRequest.device_types)
  return _internal_device_types();
}
inline ::google::protobuf::RepeatedField<int>* UpdateUserOnlineStatusRequest::mutable_device_types() {
  // @@protoc_insertion_point(field_mutable_list:turms.client.model.proto.UpdateUserOnlineStatusRequest.device_types)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_device_types();
}
inline const ::google::protobuf::RepeatedField<int>& UpdateUserOnlineStatusRequest::_internal_device_types() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.device_types_;
}
inline ::google::protobuf::RepeatedField<int>* UpdateUserOnlineStatusRequest::_internal_mutable_device_types() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.device_types_;
}

// .turms.client.model.proto.UserStatus user_status = 2;
inline void UpdateUserOnlineStatusRequest::clear_user_status() {
  _impl_.user_status_ = 0;
}
inline ::turms::client::model::proto::UserStatus UpdateUserOnlineStatusRequest::user_status() const {
  // @@protoc_insertion_point(field_get:turms.client.model.proto.UpdateUserOnlineStatusRequest.user_status)
  return _internal_user_status();
}
inline void UpdateUserOnlineStatusRequest::set_user_status(::turms::client::model::proto::UserStatus value) {
  _internal_set_user_status(value);
  // @@protoc_insertion_point(field_set:turms.client.model.proto.UpdateUserOnlineStatusRequest.user_status)
}
inline ::turms::client::model::proto::UserStatus UpdateUserOnlineStatusRequest::_internal_user_status() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::turms::client::model::proto::UserStatus>(_impl_.user_status_);
}
inline void UpdateUserOnlineStatusRequest::_internal_set_user_status(::turms::client::model::proto::UserStatus value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.user_status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_request_2fuser_2fupdate_5fuser_5fonline_5fstatus_5frequest_2eproto_2epb_2eh
