/*
 * Copyright (C) 2019 The Turms Project
 * https://github.com/turms-im/turms
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/user/query_user_ids_nearby_request.proto

package im.turms.common.model.dto.request.user;

/**
 * Protobuf type {@code im.turms.proto.QueryUserIdsNearbyRequest}
 */
public final class QueryUserIdsNearbyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.QueryUserIdsNearbyRequest)
    QueryUserIdsNearbyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryUserIdsNearbyRequest.newBuilder() to construct.
  private QueryUserIdsNearbyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryUserIdsNearbyRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryUserIdsNearbyRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryUserIdsNearbyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            latitude_ = input.readFloat();
            break;
          }
          case 21: {

            longitude_ = input.readFloat();
            break;
          }
          case 29: {
            bitField0_ |= 0x00000001;
            distance_ = input.readFloat();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000002;
            maxNumber_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOuterClass.internal_static_im_turms_proto_QueryUserIdsNearbyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOuterClass.internal_static_im_turms_proto_QueryUserIdsNearbyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.class, im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.Builder.class);
  }

  private int bitField0_;
  public static final int LATITUDE_FIELD_NUMBER = 1;
  private float latitude_;
  /**
   * <code>float latitude = 1;</code>
   * @return The latitude.
   */
  @java.lang.Override
  public float getLatitude() {
    return latitude_;
  }

  public static final int LONGITUDE_FIELD_NUMBER = 2;
  private float longitude_;
  /**
   * <code>float longitude = 2;</code>
   * @return The longitude.
   */
  @java.lang.Override
  public float getLongitude() {
    return longitude_;
  }

  public static final int DISTANCE_FIELD_NUMBER = 3;
  private float distance_;
  /**
   * <code>float distance = 3;</code>
   * @return Whether the distance field is set.
   */
  @java.lang.Override
  public boolean hasDistance() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>float distance = 3;</code>
   * @return The distance.
   */
  @java.lang.Override
  public float getDistance() {
    return distance_;
  }

  public static final int MAX_NUMBER_FIELD_NUMBER = 4;
  private int maxNumber_;
  /**
   * <code>int32 max_number = 4;</code>
   * @return Whether the maxNumber field is set.
   */
  @java.lang.Override
  public boolean hasMaxNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>int32 max_number = 4;</code>
   * @return The maxNumber.
   */
  @java.lang.Override
  public int getMaxNumber() {
    return maxNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (latitude_ != 0F) {
      output.writeFloat(1, latitude_);
    }
    if (longitude_ != 0F) {
      output.writeFloat(2, longitude_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFloat(3, distance_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(4, maxNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (latitude_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, latitude_);
    }
    if (longitude_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, longitude_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, distance_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest)) {
      return super.equals(obj);
    }
    im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest other = (im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest) obj;

    if (java.lang.Float.floatToIntBits(getLatitude())
        != java.lang.Float.floatToIntBits(
            other.getLatitude())) return false;
    if (java.lang.Float.floatToIntBits(getLongitude())
        != java.lang.Float.floatToIntBits(
            other.getLongitude())) return false;
    if (hasDistance() != other.hasDistance()) return false;
    if (hasDistance()) {
      if (java.lang.Float.floatToIntBits(getDistance())
          != java.lang.Float.floatToIntBits(
              other.getDistance())) return false;
    }
    if (hasMaxNumber() != other.hasMaxNumber()) return false;
    if (hasMaxNumber()) {
      if (getMaxNumber()
          != other.getMaxNumber()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLatitude());
    hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLongitude());
    if (hasDistance()) {
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDistance());
    }
    if (hasMaxNumber()) {
      hash = (37 * hash) + MAX_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMaxNumber();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.QueryUserIdsNearbyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.QueryUserIdsNearbyRequest)
      im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOuterClass.internal_static_im_turms_proto_QueryUserIdsNearbyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOuterClass.internal_static_im_turms_proto_QueryUserIdsNearbyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.class, im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.Builder.class);
    }

    // Construct using im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      latitude_ = 0F;

      longitude_ = 0F;

      distance_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000001);
      maxNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequestOuterClass.internal_static_im_turms_proto_QueryUserIdsNearbyRequest_descriptor;
    }

    @java.lang.Override
    public im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest getDefaultInstanceForType() {
      return im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest build() {
      im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest buildPartial() {
      im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest result = new im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.latitude_ = latitude_;
      result.longitude_ = longitude_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.distance_ = distance_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxNumber_ = maxNumber_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest) {
        return mergeFrom((im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest other) {
      if (other == im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest.getDefaultInstance()) return this;
      if (other.getLatitude() != 0F) {
        setLatitude(other.getLatitude());
      }
      if (other.getLongitude() != 0F) {
        setLongitude(other.getLongitude());
      }
      if (other.hasDistance()) {
        setDistance(other.getDistance());
      }
      if (other.hasMaxNumber()) {
        setMaxNumber(other.getMaxNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private float latitude_ ;
    /**
     * <code>float latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public float getLatitude() {
      return latitude_;
    }
    /**
     * <code>float latitude = 1;</code>
     * @param value The latitude to set.
     * @return This builder for chaining.
     */
    public Builder setLatitude(float value) {

      latitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float latitude = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatitude() {

      latitude_ = 0F;
      onChanged();
      return this;
    }

    private float longitude_ ;
    /**
     * <code>float longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public float getLongitude() {
      return longitude_;
    }
    /**
     * <code>float longitude = 2;</code>
     * @param value The longitude to set.
     * @return This builder for chaining.
     */
    public Builder setLongitude(float value) {

      longitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float longitude = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongitude() {

      longitude_ = 0F;
      onChanged();
      return this;
    }

    private float distance_ ;
    /**
     * <code>float distance = 3;</code>
     * @return Whether the distance field is set.
     */
    @java.lang.Override
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>float distance = 3;</code>
     * @return The distance.
     */
    @java.lang.Override
    public float getDistance() {
      return distance_;
    }
    /**
     * <code>float distance = 3;</code>
     * @param value The distance to set.
     * @return This builder for chaining.
     */
    public Builder setDistance(float value) {
      bitField0_ |= 0x00000001;
      distance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float distance = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistance() {
      bitField0_ = (bitField0_ & ~0x00000001);
      distance_ = 0F;
      onChanged();
      return this;
    }

    private int maxNumber_ ;
    /**
     * <code>int32 max_number = 4;</code>
     * @return Whether the maxNumber field is set.
     */
    @java.lang.Override
    public boolean hasMaxNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int32 max_number = 4;</code>
     * @return The maxNumber.
     */
    @java.lang.Override
    public int getMaxNumber() {
      return maxNumber_;
    }
    /**
     * <code>int32 max_number = 4;</code>
     * @param value The maxNumber to set.
     * @return This builder for chaining.
     */
    public Builder setMaxNumber(int value) {
      bitField0_ |= 0x00000002;
      maxNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxNumber_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.QueryUserIdsNearbyRequest)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.QueryUserIdsNearbyRequest)
  private static final im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest();
  }

  public static im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryUserIdsNearbyRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueryUserIdsNearbyRequest>() {
    @java.lang.Override
    public QueryUserIdsNearbyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryUserIdsNearbyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryUserIdsNearbyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryUserIdsNearbyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.turms.common.model.dto.request.user.QueryUserIdsNearbyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

