// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request/message/create_message_request.proto
// Protobuf C++ Version: 5.27.2

#include "turms/client/model/proto/request/message/create_message_request.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace turms {
namespace client {
namespace model {
namespace proto {

inline constexpr CreateMessageRequest::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      records_{},
      custom_attributes_{},
      text_(&::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
      message_id_{::int64_t{0}},
      group_id_{::int64_t{0}},
      recipient_id_{::int64_t{0}},
      delivery_date_{::int64_t{0}},
      is_system_message_{false},
      burn_after_{0},
      pre_message_id_{::int64_t{0}} {
}

template <typename>
PROTOBUF_CONSTEXPR CreateMessageRequest::CreateMessageRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateMessageRequestDefaultTypeInternal {
    PROTOBUF_CONSTEXPR CreateMessageRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{}) {
    }
    ~CreateMessageRequestDefaultTypeInternal() {
    }
    union {
        CreateMessageRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    CreateMessageRequestDefaultTypeInternal _CreateMessageRequest_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace turms {
namespace client {
namespace model {
namespace proto {
// ===================================================================

class CreateMessageRequest::_Internal {
   public:
    using HasBits = decltype(std::declval<CreateMessageRequest>()._impl_._has_bits_);
    static constexpr ::int32_t kHasBitsOffset =
        8 * PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_._has_bits_);
};

void CreateMessageRequest::clear_custom_attributes() {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.custom_attributes_.Clear();
}
CreateMessageRequest::CreateMessageRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:turms.client.model.proto.CreateMessageRequest)
}
inline PROTOBUF_NDEBUG_INLINE CreateMessageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena,
    const Impl_& from,
    const ::turms::client::model::proto::CreateMessageRequest& from_msg)
    : _has_bits_{from._has_bits_},
      _cached_size_{0},
      records_{visibility, arena, from.records_},
      custom_attributes_{visibility, arena, from.custom_attributes_},
      text_(arena, from.text_) {
}

CreateMessageRequest::CreateMessageRequest(::google::protobuf::Arena* arena,
                                           const CreateMessageRequest& from)
    : ::google::protobuf::MessageLite(arena) {
    CreateMessageRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
    new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    ::memcpy(reinterpret_cast<char*>(&_impl_) + offsetof(Impl_, message_id_),
             reinterpret_cast<const char*>(&from._impl_) + offsetof(Impl_, message_id_),
             offsetof(Impl_, pre_message_id_) - offsetof(Impl_, message_id_) +
                 sizeof(Impl_::pre_message_id_));

    // @@protoc_insertion_point(copy_constructor:turms.client.model.proto.CreateMessageRequest)
}
inline PROTOBUF_NDEBUG_INLINE CreateMessageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena)
    : _cached_size_{0},
      records_{visibility, arena},
      custom_attributes_{visibility, arena},
      text_(arena) {
}

inline void CreateMessageRequest::SharedCtor(::_pb::Arena* arena) {
    new (&_impl_) Impl_(internal_visibility(), arena);
    ::memset(reinterpret_cast<char*>(&_impl_) + offsetof(Impl_, message_id_),
             0,
             offsetof(Impl_, pre_message_id_) - offsetof(Impl_, message_id_) +
                 sizeof(Impl_::pre_message_id_));
}
CreateMessageRequest::~CreateMessageRequest() {
    // @@protoc_insertion_point(destructor:turms.client.model.proto.CreateMessageRequest)
    _internal_metadata_.Delete<std::string>();
    SharedDtor();
}
inline void CreateMessageRequest::SharedDtor() {
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.text_.Destroy();
    _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData* CreateMessageRequest::GetClassData() const {
    PROTOBUF_CONSTINIT static const ClassDataLite<46> _data_ = {
        {
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_._cached_size_),
            true,
        },
        "turms.client.model.proto.CreateMessageRequest",
    };

    return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<4, 10, 1, 66, 2>
    CreateMessageRequest::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_._has_bits_),
            0,  // no _extensions_
            15,
            120,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294950400,  // skipmap
            offsetof(decltype(_table_), field_entries),
            10,  // num_field_entries
            1,   // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            &_CreateMessageRequest_default_instance_._instance,
            nullptr,                                // post_loop_handler
            ::_pbi::TcParser::GenericFallbackLite,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::turms::client::model::proto::CreateMessageRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
            // optional int64 message_id = 1;
            {::_pbi::TcParser::FastV64S1,
             {8, 1, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.message_id_)}},
            // optional bool is_system_message = 2;
            {::_pbi::TcParser::FastV8S1,
             {16, 5, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.is_system_message_)}},
            // optional int64 group_id = 3;
            {::_pbi::TcParser::FastV64S1,
             {24, 2, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.group_id_)}},
            // optional int64 recipient_id = 4;
            {::_pbi::TcParser::FastV64S1,
             {32, 3, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.recipient_id_)}},
            // optional int64 delivery_date = 5;
            {::_pbi::TcParser::FastV64S1,
             {40, 4, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.delivery_date_)}},
            // optional string text = 6;
            {::_pbi::TcParser::FastUS1,
             {50, 0, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.text_)}},
            // repeated bytes records = 7;
            {::_pbi::TcParser::FastBR1,
             {58, 63, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.records_)}},
            // optional int32 burn_after = 8;
            {::_pbi::TcParser::FastV32S1,
             {64, 6, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.burn_after_)}},
            // optional int64 pre_message_id = 9;
            {::_pbi::TcParser::FastV64S1,
             {72, 7, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.pre_message_id_)}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            // repeated .turms.client.model.proto.Value custom_attributes = 15;
            {::_pbi::TcParser::FastMtR1,
             {122, 63, 0, PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.custom_attributes_)}},
        }},
        {{65535, 65535}},
        {{
            // optional int64 message_id = 1;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.message_id_),
             _Internal::kHasBitsOffset + 1,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional bool is_system_message = 2;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.is_system_message_),
             _Internal::kHasBitsOffset + 5,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kBool)},
            // optional int64 group_id = 3;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.group_id_),
             _Internal::kHasBitsOffset + 2,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional int64 recipient_id = 4;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.recipient_id_),
             _Internal::kHasBitsOffset + 3,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional int64 delivery_date = 5;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.delivery_date_),
             _Internal::kHasBitsOffset + 4,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional string text = 6;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.text_),
             _Internal::kHasBitsOffset + 0,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // repeated bytes records = 7;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.records_),
             -1,
             0,
             (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
            // optional int32 burn_after = 8;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.burn_after_),
             _Internal::kHasBitsOffset + 6,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
            // optional int64 pre_message_id = 9;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.pre_message_id_),
             _Internal::kHasBitsOffset + 7,
             0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // repeated .turms.client.model.proto.Value custom_attributes = 15;
            {PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.custom_attributes_),
             -1,
             0,
             (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
        }},
        {{
            {::_pbi::TcParser::GetTable<::turms::client::model::proto::Value>()},
        }},
        {{"\55\0\0\0\0\0\4\0\0\0\0\0\0\0\0\0"
          "turms.client.model.proto.CreateMessageRequest"
          "text"}},
};

PROTOBUF_NOINLINE void CreateMessageRequest::Clear() {
    // @@protoc_insertion_point(message_clear_start:turms.client.model.proto.CreateMessageRequest)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.records_.Clear();
    _impl_.custom_attributes_.Clear();
    cached_has_bits = _impl_._has_bits_[0];
    if (cached_has_bits & 0x00000001u) {
        _impl_.text_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x000000feu) {
        ::memset(&_impl_.message_id_,
                 0,
                 static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.pre_message_id_) -
                                       reinterpret_cast<char*>(&_impl_.message_id_)) +
                     sizeof(_impl_.pre_message_id_));
    }
    _impl_._has_bits_.Clear();
    _internal_metadata_.Clear<std::string>();
}

::uint8_t* CreateMessageRequest::_InternalSerialize(
    ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    // @@protoc_insertion_point(serialize_to_array_start:turms.client.model.proto.CreateMessageRequest)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    cached_has_bits = _impl_._has_bits_[0];
    // optional int64 message_id = 1;
    if (cached_has_bits & 0x00000002u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this->_internal_message_id(), target);
    }

    // optional bool is_system_message = 2;
    if (cached_has_bits & 0x00000020u) {
        target = stream->EnsureSpace(target);
        target = ::_pbi::WireFormatLite::WriteBoolToArray(
            2, this->_internal_is_system_message(), target);
    }

    // optional int64 group_id = 3;
    if (cached_has_bits & 0x00000004u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
            stream, this->_internal_group_id(), target);
    }

    // optional int64 recipient_id = 4;
    if (cached_has_bits & 0x00000008u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
            stream, this->_internal_recipient_id(), target);
    }

    // optional int64 delivery_date = 5;
    if (cached_has_bits & 0x00000010u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
            stream, this->_internal_delivery_date(), target);
    }

    // optional string text = 6;
    if (cached_has_bits & 0x00000001u) {
        const std::string& _s = this->_internal_text();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(),
            static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "turms.client.model.proto.CreateMessageRequest.text");
        target = stream->WriteStringMaybeAliased(6, _s, target);
    }

    // repeated bytes records = 7;
    for (int i = 0, n = this->_internal_records_size(); i < n; ++i) {
        const auto& s = this->_internal_records().Get(i);
        target = stream->WriteBytes(7, s, target);
    }

    // optional int32 burn_after = 8;
    if (cached_has_bits & 0x00000040u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<8>(
            stream, this->_internal_burn_after(), target);
    }

    // optional int64 pre_message_id = 9;
    if (cached_has_bits & 0x00000080u) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<9>(
            stream, this->_internal_pre_message_id(), target);
    }

    // repeated .turms.client.model.proto.Value custom_attributes = 15;
    for (unsigned i = 0, n = static_cast<unsigned>(this->_internal_custom_attributes_size()); i < n;
         i++) {
        const auto& repfield = this->_internal_custom_attributes().Get(i);
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            15, repfield, repfield.GetCachedSize(), target, stream);
    }

    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
        target = stream->WriteRaw(
            _internal_metadata_
                .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                .data(),
            static_cast<int>(
                _internal_metadata_
                    .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                    .size()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:turms.client.model.proto.CreateMessageRequest)
    return target;
}

::size_t CreateMessageRequest::ByteSizeLong() const {
    // @@protoc_insertion_point(message_byte_size_start:turms.client.model.proto.CreateMessageRequest)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
    // repeated bytes records = 7;
    total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_records().size());
    for (int i = 0, n = _internal_records().size(); i < n; ++i) {
        total_size +=
            ::google::protobuf::internal::WireFormatLite::BytesSize(_internal_records().Get(i));
    }
    // repeated .turms.client.model.proto.Value custom_attributes = 15;
    total_size += 1UL * this->_internal_custom_attributes_size();
    for (const auto& msg : this->_internal_custom_attributes()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
    }
    cached_has_bits = _impl_._has_bits_[0];
    if (cached_has_bits & 0x000000ffu) {
        // optional string text = 6;
        if (cached_has_bits & 0x00000001u) {
            total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                  this->_internal_text());
        }

        // optional int64 message_id = 1;
        if (cached_has_bits & 0x00000002u) {
            total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_message_id());
        }

        // optional int64 group_id = 3;
        if (cached_has_bits & 0x00000004u) {
            total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_group_id());
        }

        // optional int64 recipient_id = 4;
        if (cached_has_bits & 0x00000008u) {
            total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_recipient_id());
        }

        // optional int64 delivery_date = 5;
        if (cached_has_bits & 0x00000010u) {
            total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_delivery_date());
        }

        // optional bool is_system_message = 2;
        if (cached_has_bits & 0x00000020u) {
            total_size += 2;
        }

        // optional int32 burn_after = 8;
        if (cached_has_bits & 0x00000040u) {
            total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_burn_after());
        }

        // optional int64 pre_message_id = 9;
        if (cached_has_bits & 0x00000080u) {
            total_size +=
                ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_pre_message_id());
        }
    }
    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
        total_size += _internal_metadata_
                          .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                          .size();
    }
    _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
    return total_size;
}

void CreateMessageRequest::CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from) {
    MergeFrom(*::_pbi::DownCast<const CreateMessageRequest*>(&from));
}

void CreateMessageRequest::MergeFrom(const CreateMessageRequest& from) {
    CreateMessageRequest* const _this = this;
    // @@protoc_insertion_point(class_specific_merge_from_start:turms.client.model.proto.CreateMessageRequest)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    _this->_internal_mutable_records()->MergeFrom(from._internal_records());
    _this->_internal_mutable_custom_attributes()->MergeFrom(from._internal_custom_attributes());
    cached_has_bits = from._impl_._has_bits_[0];
    if (cached_has_bits & 0x000000ffu) {
        if (cached_has_bits & 0x00000001u) {
            _this->_internal_set_text(from._internal_text());
        }
        if (cached_has_bits & 0x00000002u) {
            _this->_impl_.message_id_ = from._impl_.message_id_;
        }
        if (cached_has_bits & 0x00000004u) {
            _this->_impl_.group_id_ = from._impl_.group_id_;
        }
        if (cached_has_bits & 0x00000008u) {
            _this->_impl_.recipient_id_ = from._impl_.recipient_id_;
        }
        if (cached_has_bits & 0x00000010u) {
            _this->_impl_.delivery_date_ = from._impl_.delivery_date_;
        }
        if (cached_has_bits & 0x00000020u) {
            _this->_impl_.is_system_message_ = from._impl_.is_system_message_;
        }
        if (cached_has_bits & 0x00000040u) {
            _this->_impl_.burn_after_ = from._impl_.burn_after_;
        }
        if (cached_has_bits & 0x00000080u) {
            _this->_impl_.pre_message_id_ = from._impl_.pre_message_id_;
        }
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
    _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CreateMessageRequest::CopyFrom(const CreateMessageRequest& from) {
    // @@protoc_insertion_point(class_specific_copy_from_start:turms.client.model.proto.CreateMessageRequest)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void CreateMessageRequest::InternalSwap(CreateMessageRequest* PROTOBUF_RESTRICT other) {
    using std::swap;
    auto* arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
    _impl_.records_.InternalSwap(&other->_impl_.records_);
    _impl_.custom_attributes_.InternalSwap(&other->_impl_.custom_attributes_);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
    ::google::protobuf::internal::memswap<
        PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.pre_message_id_) +
        sizeof(CreateMessageRequest::_impl_.pre_message_id_) -
        PROTOBUF_FIELD_OFFSET(CreateMessageRequest, _impl_.message_id_)>(
        reinterpret_cast<char*>(&_impl_.message_id_),
        reinterpret_cast<char*>(&other->_impl_.message_id_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"