import TurmsDriver from './driver/turms-driver';
import UserService from './service/user-service';
import GroupService from './service/group-service';
import ConversationService from './service/conversation-service';
import MessageService from './service/message-service';
import NotificationService from './service/notification-service';
import InputFileReader from './util/input-file-reader';
import StorageService from './service/storage-service';
import ClientOptions from './client-options';
declare class TurmsClient {
    private readonly _driver;
    private readonly _userService;
    private readonly _groupService;
    private readonly _conversationService;
    private readonly _messageService;
    private readonly _storageService;
    private readonly _notificationService;
    constructor(options?: ClientOptions);
    constructor(wsUrl?: string, connectionTimeout?: number, requestTimeout?: number, minRequestInterval?: number, heartbeatInterval?: number, storageServerUrl?: string);
    get driver(): TurmsDriver;
    get userService(): UserService;
    get groupService(): GroupService;
    get conversationService(): ConversationService;
    get messageService(): MessageService;
    get storageService(): StorageService;
    get notificationService(): NotificationService;
    static InputFileReader(): InputFileReader;
    close(): Promise<void>;
}
export default TurmsClient;
