declare enum TurmsCloseStatus {
    SWITCH = 300,
    ILLEGAL_REQUEST = 400,
    HEARTBEAT_TIMEOUT = 401,
    DISCONNECTED_BY_CLIENT = 402,
    DISCONNECTED_BY_OTHER_DEVICE = 403,
    SERVER_ERROR = 500,
    SERVER_CLOSED = 501,
    SERVER_UNAVAILABLE = 502,
    LOGIN_CONFLICT = 600,
    LOGIN_TIMEOUT = 601,
    DISCONNECTED_BY_ADMIN = 700,
    USER_IS_DELETED_OR_INACTIVATED = 701,
    UNKNOWN_ERROR = 900
}
export default TurmsCloseStatus;
