// Autogenerated from Pigeon (v17.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "app_host_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace turms_chat_demo {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// DiskSpaceInfo

DiskSpaceInfo::DiskSpaceInfo(
  int64_t total,
  int64_t free,
  int64_t usable)
 : total_(total),
    free_(free),
    usable_(usable) {}

int64_t DiskSpaceInfo::total() const {
  return total_;
}

void DiskSpaceInfo::set_total(int64_t value_arg) {
  total_ = value_arg;
}


int64_t DiskSpaceInfo::free() const {
  return free_;
}

void DiskSpaceInfo::set_free(int64_t value_arg) {
  free_ = value_arg;
}


int64_t DiskSpaceInfo::usable() const {
  return usable_;
}

void DiskSpaceInfo::set_usable(int64_t value_arg) {
  usable_ = value_arg;
}


EncodableList DiskSpaceInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(total_));
  list.push_back(EncodableValue(free_));
  list.push_back(EncodableValue(usable_));
  return list;
}

DiskSpaceInfo DiskSpaceInfo::FromEncodableList(const EncodableList& list) {
  DiskSpaceInfo decoded(
    list[0].LongValue(),
    list[1].LongValue(),
    list[2].LongValue());
  return decoded;
}


AppHostApiCodecSerializer::AppHostApiCodecSerializer() {}

EncodableValue AppHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(DiskSpaceInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void AppHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DiskSpaceInfo)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<DiskSpaceInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by AppHostApi.
const flutter::StandardMessageCodec& AppHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&AppHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `AppHostApi` to handle messages through the `binary_messenger`.
void AppHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  AppHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.turms_chat_demo.AppHostApi.getDiskSpace", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          ErrorOr<DiskSpaceInfo> output = api->GetDiskSpace(path_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue AppHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue AppHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace turms_chat_demo
