# The file is used by tests of servers

services:
  # MongoDB
  mongodb-router:
    image: "bitnami/mongodb-sharded:7.0.15"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-router
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-config
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=turms
    healthcheck:
      # Use "mongo -u root -p turms --port 27017 --eval='sh.status()' | grep mongodb-shard | grep -q '\"state\" : 1'" before v5.0
      test: "mongosh -u root -p turms --port 27017 --eval='sh.status()' | sed -n '/shards/,/---/p' | grep -q 'state: 1'"
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-shard:
    image: "bitnami/mongodb-sharded:7.0.15"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-router
      - MONGODB_ROOT_PASSWORD=turms
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard01

  mongodb-config:
    image: "bitnami/mongodb-sharded:7.0.15"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-config
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=turms
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset

  # Redis
  redis:
    image: redis:7.4.1-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    healthcheck:
      test: mc ready local
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch
  elasticsearch:
    image: 'elasticsearch:8.17.0'
    environment:
      cluster.routing.allocation.disk.threshold_enabled: false
      discovery.type: single-node
      xpack.security.enabled: false
    command:
      - /bin/bash
      - -c
      - |
        PLUGINS=$(bin/elasticsearch-plugin list)
        echo "Installed plugins: ${PLUGINS}"
        echo "${PLUGINS}" | grep -q analysis-ik || bin/elasticsearch-plugin install --batch --verbose "https://get.infini.cloud/elasticsearch/analysis-ik/8.17.0" || (echo "failed to the plugin: analysis-ik" && exit 1)
        echo "${PLUGINS}" | grep -q analysis-icu || bin/elasticsearch-plugin install --batch --verbose analysis-icu || (echo "failed to the plugin: analysis-icu" && exit 1)
        echo "${PLUGINS}" | grep -q analysis-kuromoji || bin/elasticsearch-plugin install --batch --verbose analysis-kuromoji || (echo "failed to the plugin: analysis-kuromoji" && exit 1)
        /usr/local/bin/docker-entrypoint.sh
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -fsSL http://localhost:9200/_cat/health?h=status | grep -q -E 'green|yellow'",
      ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1m

  # turms servers
  turms-admin:
    image: "ghcr.io/turms-im/turms-admin"

  turms-gateway:
    image: "ghcr.io/turms-im/turms-gateway"
    depends_on:
      mongodb-router:
        condition: service_healthy
      redis:
        condition: service_healthy
      turms-service:
        condition: service_healthy
    environment:
      TURMS_GATEWAY_JVM_OPTS: >
        -Dspring.profiles.active=test

        -Dturms.cluster.connection.server.port=7610
        -Dturms.cluster.connection.server.port-auto-increment=false

        -Dturms.cluster.discovery.address.advertise-strategy=advertise_address
        -Dturms.cluster.discovery.address.advertise-host=turms-gateway

        -Dturms.cluster.shared-config.mongo.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.gateway.mongo.admin.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.gateway.mongo.user.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin

        -Dturms.gateway.redis.session.uri-list[0]=redis://redis:6379
        -Dturms.gateway.redis.location.uri-list[0]=redis://redis:6379
        -Dturms.gateway.redis.ip-blocklist.uri=redis://redis:6379
        -Dturms.gateway.redis.user-id-blocklist.uri=redis://redis:6379
    healthcheck:
      test: "curl --fail --silent --user turms:turms turms-gateway:9510/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000

  turms-service:
    image: "ghcr.io/turms-im/turms-service"
    depends_on:
      mongodb-router:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TURMS_SERVICE_JVM_OPTS: >
        -Dspring.profiles.active=test

        -Dturms.cluster.connection.server.port-auto-increment=false

        -Dturms.cluster.discovery.address.advertise-strategy=advertise_address
        -Dturms.cluster.discovery.address.advertise-host=turms-service

        -Dturms.cluster.shared-config.mongo.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.admin.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.user.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.group.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.conversation.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.message.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin
        -Dturms.service.mongo.conference.uri=mongodb://root:turms@mongodb-router:27017/turms-standalone?authSource=admin

        -Dturms.service.redis.sequence-id.uri-list[0]=redis://redis:6379
        -Dturms.service.redis.session.uri-list[0]=redis://redis:6379
        -Dturms.service.redis.location.uri-list[0]=redis://redis:6379
        -Dturms.service.redis.ip-blocklist.uri=redis://redis:6379
        -Dturms.service.redis.user-id-blocklist.uri=redis://redis:6379
    healthcheck:
      test: "curl --fail --silent --user turms:turms turms-service:8510/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536