// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request/group/blocklist/create_group_blocked_user_request.proto
// Protobuf C++ Version: 5.27.2

#include "turms/client/model/proto/request/group/blocklist/create_group_blocked_user_request.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace turms {
namespace client {
namespace model {
namespace proto {

inline constexpr CreateGroupBlockedUserRequest::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : custom_attributes_{},
      group_id_{::int64_t{0}},
      user_id_{::int64_t{0}},
      _cached_size_{0} {
}

template <typename>
PROTOBUF_CONSTEXPR CreateGroupBlockedUserRequest::CreateGroupBlockedUserRequest(
    ::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateGroupBlockedUserRequestDefaultTypeInternal {
    PROTOBUF_CONSTEXPR CreateGroupBlockedUserRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{}) {
    }
    ~CreateGroupBlockedUserRequestDefaultTypeInternal() {
    }
    union {
        CreateGroupBlockedUserRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    CreateGroupBlockedUserRequestDefaultTypeInternal
        _CreateGroupBlockedUserRequest_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace turms {
namespace client {
namespace model {
namespace proto {
// ===================================================================

class CreateGroupBlockedUserRequest::_Internal {
   public:
};

void CreateGroupBlockedUserRequest::clear_custom_attributes() {
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.custom_attributes_.Clear();
}
CreateGroupBlockedUserRequest::CreateGroupBlockedUserRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:turms.client.model.proto.CreateGroupBlockedUserRequest)
}
inline PROTOBUF_NDEBUG_INLINE CreateGroupBlockedUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena,
    const Impl_& from,
    const ::turms::client::model::proto::CreateGroupBlockedUserRequest& from_msg)
    : custom_attributes_{visibility, arena, from.custom_attributes_},
      _cached_size_{0} {
}

CreateGroupBlockedUserRequest::CreateGroupBlockedUserRequest(
    ::google::protobuf::Arena* arena, const CreateGroupBlockedUserRequest& from)
    : ::google::protobuf::MessageLite(arena) {
    CreateGroupBlockedUserRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
    new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    ::memcpy(reinterpret_cast<char*>(&_impl_) + offsetof(Impl_, group_id_),
             reinterpret_cast<const char*>(&from._impl_) + offsetof(Impl_, group_id_),
             offsetof(Impl_, user_id_) - offsetof(Impl_, group_id_) + sizeof(Impl_::user_id_));

    // @@protoc_insertion_point(copy_constructor:turms.client.model.proto.CreateGroupBlockedUserRequest)
}
inline PROTOBUF_NDEBUG_INLINE CreateGroupBlockedUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena)
    : custom_attributes_{visibility, arena},
      _cached_size_{0} {
}

inline void CreateGroupBlockedUserRequest::SharedCtor(::_pb::Arena* arena) {
    new (&_impl_) Impl_(internal_visibility(), arena);
    ::memset(reinterpret_cast<char*>(&_impl_) + offsetof(Impl_, group_id_),
             0,
             offsetof(Impl_, user_id_) - offsetof(Impl_, group_id_) + sizeof(Impl_::user_id_));
}
CreateGroupBlockedUserRequest::~CreateGroupBlockedUserRequest() {
    // @@protoc_insertion_point(destructor:turms.client.model.proto.CreateGroupBlockedUserRequest)
    _internal_metadata_.Delete<std::string>();
    SharedDtor();
}
inline void CreateGroupBlockedUserRequest::SharedDtor() {
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData* CreateGroupBlockedUserRequest::GetClassData()
    const {
    PROTOBUF_CONSTINIT static const ClassDataLite<55> _data_ = {
        {
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_._cached_size_),
            true,
        },
        "turms.client.model.proto.CreateGroupBlockedUserRequest",
    };

    return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<2, 3, 1, 0, 2>
    CreateGroupBlockedUserRequest::_table_ = {
        {
            0,  // no _has_bits_
            0,  // no _extensions_
            15,
            24,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294950908,  // skipmap
            offsetof(decltype(_table_), field_entries),
            3,  // num_field_entries
            1,  // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            &_CreateGroupBlockedUserRequest_default_instance_._instance,
            nullptr,                                // post_loop_handler
            ::_pbi::TcParser::GenericFallbackLite,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::turms::client::model::proto::CreateGroupBlockedUserRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
            // int64 group_id = 1;
            {::_pbi::TcParser::FastV64S1,
             {8, 63, 0, PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.group_id_)}},
            // int64 user_id = 2;
            {::_pbi::TcParser::FastV64S1,
             {16, 63, 0, PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.user_id_)}},
            // repeated .turms.client.model.proto.Value custom_attributes = 15;
            {::_pbi::TcParser::FastMtR1,
             {122,
              63,
              0,
              PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.custom_attributes_)}},
        }},
        {{65535, 65535}},
        {{
            // int64 group_id = 1;
            {PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.group_id_),
             0,
             0,
             (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
            // int64 user_id = 2;
            {PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.user_id_),
             0,
             0,
             (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
            // repeated .turms.client.model.proto.Value custom_attributes = 15;
            {PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.custom_attributes_),
             0,
             0,
             (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
        }},
        {{
            {::_pbi::TcParser::GetTable<::turms::client::model::proto::Value>()},
        }},
        {{}},
};

PROTOBUF_NOINLINE void CreateGroupBlockedUserRequest::Clear() {
    // @@protoc_insertion_point(message_clear_start:turms.client.model.proto.CreateGroupBlockedUserRequest)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.custom_attributes_.Clear();
    ::memset(&_impl_.group_id_,
             0,
             static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.user_id_) -
                                   reinterpret_cast<char*>(&_impl_.group_id_)) +
                 sizeof(_impl_.user_id_));
    _internal_metadata_.Clear<std::string>();
}

::uint8_t* CreateGroupBlockedUserRequest::_InternalSerialize(
    ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    // @@protoc_insertion_point(serialize_to_array_start:turms.client.model.proto.CreateGroupBlockedUserRequest)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // int64 group_id = 1;
    if (this->_internal_group_id() != 0) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this->_internal_group_id(), target);
    }

    // int64 user_id = 2;
    if (this->_internal_user_id() != 0) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
            stream, this->_internal_user_id(), target);
    }

    // repeated .turms.client.model.proto.Value custom_attributes = 15;
    for (unsigned i = 0, n = static_cast<unsigned>(this->_internal_custom_attributes_size()); i < n;
         i++) {
        const auto& repfield = this->_internal_custom_attributes().Get(i);
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            15, repfield, repfield.GetCachedSize(), target, stream);
    }

    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
        target = stream->WriteRaw(
            _internal_metadata_
                .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                .data(),
            static_cast<int>(
                _internal_metadata_
                    .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                    .size()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:turms.client.model.proto.CreateGroupBlockedUserRequest)
    return target;
}

::size_t CreateGroupBlockedUserRequest::ByteSizeLong() const {
    // @@protoc_insertion_point(message_byte_size_start:turms.client.model.proto.CreateGroupBlockedUserRequest)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
    // repeated .turms.client.model.proto.Value custom_attributes = 15;
    total_size += 1UL * this->_internal_custom_attributes_size();
    for (const auto& msg : this->_internal_custom_attributes()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
    }
    // int64 group_id = 1;
    if (this->_internal_group_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_group_id());
    }

    // int64 user_id = 2;
    if (this->_internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_user_id());
    }

    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
        total_size += _internal_metadata_
                          .unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString)
                          .size();
    }
    _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
    return total_size;
}

void CreateGroupBlockedUserRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
    MergeFrom(*::_pbi::DownCast<const CreateGroupBlockedUserRequest*>(&from));
}

void CreateGroupBlockedUserRequest::MergeFrom(const CreateGroupBlockedUserRequest& from) {
    CreateGroupBlockedUserRequest* const _this = this;
    // @@protoc_insertion_point(class_specific_merge_from_start:turms.client.model.proto.CreateGroupBlockedUserRequest)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    _this->_internal_mutable_custom_attributes()->MergeFrom(from._internal_custom_attributes());
    if (from._internal_group_id() != 0) {
        _this->_impl_.group_id_ = from._impl_.group_id_;
    }
    if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
    }
    _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CreateGroupBlockedUserRequest::CopyFrom(const CreateGroupBlockedUserRequest& from) {
    // @@protoc_insertion_point(class_specific_copy_from_start:turms.client.model.proto.CreateGroupBlockedUserRequest)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void CreateGroupBlockedUserRequest::InternalSwap(
    CreateGroupBlockedUserRequest* PROTOBUF_RESTRICT other) {
    using std::swap;
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    _impl_.custom_attributes_.InternalSwap(&other->_impl_.custom_attributes_);
    ::google::protobuf::internal::memswap<
        PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.user_id_) +
        sizeof(CreateGroupBlockedUserRequest::_impl_.user_id_) -
        PROTOBUF_FIELD_OFFSET(CreateGroupBlockedUserRequest, _impl_.group_id_)>(
        reinterpret_cast<char*>(&_impl_.group_id_),
        reinterpret_cast<char*>(&other->_impl_.group_id_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace model
}  // namespace client
}  // namespace turms
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"