import { im } from "../model/proto-bundle";
import TurmsClient from "../turms-client";
import { ParsedNotification } from "../model/parsed-notification";
import TurmsNotification = im.turms.proto.TurmsNotification;
export default class TurmsDriver {
    private _heartbeatInterval;
    private _websocket;
    private _heartbeatTimer?;
    private _onNotificationListeners;
    private _onClose?;
    private _turmsClient;
    private _url;
    private _httpUrl;
    private _connectionTimeout;
    private _requestTimeout;
    private _minRequestsInterval;
    private _requestsMap;
    private _lastRequestDate;
    private _isLastRequestHeartbeat;
    private _queryReasonWhenLoginFailed;
    private _queryReasonWhenDisconnected;
    private _userId;
    private _password;
    private _requestId;
    private _sessionId?;
    private _address?;
    constructor(client: TurmsClient, url?: string, connectionTimeout?: number, requestTimeout?: number, minRequestsInterval?: number, httpUrl?: string, queryReasonWhenLoginFailed?: boolean, queryReasonWhenDisconnected?: boolean);
    set onClose(value: any);
    get onNotificationListeners(): ((notification: ParsedNotification) => void)[];
    sendHeartbeat(): Promise<void>;
    connected(): boolean;
    disconnect(): Promise<CloseEvent>;
    connect(userId: number, password: string, requestId: number, url?: string, connectionTimeout?: number, requestTimeout?: number): Promise<void>;
    resetHeartBeatTimer(): void;
    send(message: im.turms.proto.ITurmsRequest): Promise<TurmsNotification>;
    private _setLastRequestRecord;
    private _generateRandomId;
    private _onWebsocketOpen;
    private _onWebsocketClose;
    private _onWebsocketError;
}
