name: Test turms-client-dart

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        sdk: [3.0, stable, beta]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        working-directory: turms-client-dart
        run: dart pub get

      - name: Verify formatting
        working-directory: turms-client-dart
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: turms-client-dart
        run: dart analyze

      - name: Run tests
        working-directory: turms-client-dart
        run: dart test