name: Test turms-client-kotlin

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ '8', '17' ]
    name: Test in Java ${{ matrix.Java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Verify formatting
        run: mvn validate --projects turms-client-kotlin --activate-profiles lint --batch-mode --no-transfer-progress

      - name: Run tests
        run: mvn verify --projects turms-client-kotlin