name: Test turms-server-common

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Maven Verify
        run: mvn clean verify -am -B -pl turms-server-common --no-transfer-progress